In [3]:
import numpy as np

#### Create the array

In [4]:
x = np.array([2,4,6,8,10])

In [5]:
print (x)

[ 2  4  6  8 10]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x

array([ 2,  4,  6,  8, 10])

In [9]:
x.dtype

dtype('int32')

In [12]:
x = np.array([2,4,6,8,10], dtype=np.int8)

In [13]:
x.dtype

dtype('int8')

In [14]:
x.size

5

In [15]:
x.shape

(5,)

In [16]:
x.min()

2

In [17]:
x.max()

10

In [18]:
x.std()

2.8284271247461903

In [19]:
x.sum()

30

In [20]:
x.mean()

6.0

In [21]:
y = np.array([3,6,9.9,5,4])

In [22]:
y

array([3. , 6. , 9.9, 5. , 4. ])

In [23]:
print(y)

[3.  6.  9.9 5.  4. ]


In [24]:
y.dtype

dtype('float64')

In [26]:
z = np.array([3,6,9.9,5,4,True])

In [27]:
z.dtype

dtype('float64')

In [28]:
z

array([3. , 6. , 9.9, 5. , 4. , 1. ])

In [29]:
z = np.zeros(10, dtype=np.int16)

In [30]:
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [31]:
z = np.ones(10, dtype=np.int16)

In [32]:
z

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [37]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [38]:
np.arange(2,20,-3)

array([], dtype=int32)

In [39]:
np.arange(20,1,-3)

array([20, 17, 14, 11,  8,  5,  2])

In [40]:
np.arange(0,10,0.33)

array([0.  , 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.97, 3.3 ,
       3.63, 3.96, 4.29, 4.62, 4.95, 5.28, 5.61, 5.94, 6.27, 6.6 , 6.93,
       7.26, 7.59, 7.92, 8.25, 8.58, 8.91, 9.24, 9.57, 9.9 ])

In [41]:
np.linspace(1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [43]:
np.linspace(1,13,5)

array([ 1.,  4.,  7., 10., 13.])

#### Array Operations

In [44]:
num1 = np.array([32,45,62,76,89])
num2 = np.array([12,56,45,90,38])

In [45]:
num1 + 10

array([42, 55, 72, 86, 99])

In [46]:
num2 /5

array([ 2.4, 11.2,  9. , 18. ,  7.6])

In [47]:
num1 * 4

array([128, 180, 248, 304, 356])

In [48]:
[32,45,62,76,89] * 3

[32, 45, 62, 76, 89, 32, 45, 62, 76, 89, 32, 45, 62, 76, 89]

In [49]:
num1 + num2

array([ 44, 101, 107, 166, 127])

In [50]:
num1 - num2

array([ 20, -11,  17, -14,  51])

#### Matrix

In [54]:
M = np.array([[4,6,7],[1,2,3],[8,0,2],[9,3,5]])

In [55]:
M

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]])

In [56]:
M.ndim

2

In [57]:
M.shape

(4, 3)

In [58]:
M.size

12

In [59]:
M[2][1]

0

In [60]:
M[2,1]

0

In [61]:
M[2,2]

2

In [62]:
M[1:3 , 0:2]

array([[1, 2],
       [8, 0]])

In [63]:
 M1 = M.reshape(3,4)
M1

array([[4, 6, 7, 1],
       [2, 3, 8, 0],
       [2, 9, 3, 5]])

In [64]:
M1.reshape(6,2)

array([[4, 6],
       [7, 1],
       [2, 3],
       [8, 0],
       [2, 9],
       [3, 5]])

In [65]:
M[1:3 , 0:2] = np.array([[7,8],[0,0]])
M

array([[4, 6, 7],
       [7, 8, 3],
       [0, 0, 2],
       [9, 3, 5]])

In [66]:
M.reshape(2,-1)

array([[4, 6, 7, 7, 8, 3],
       [0, 0, 2, 9, 3, 5]])

In [67]:
M.reshape(-1,4)

array([[4, 6, 7, 7],
       [8, 3, 0, 0],
       [2, 9, 3, 5]])

In [69]:
M.reshape(-1)

array([4, 6, 7, 7, 8, 3, 0, 0, 2, 9, 3, 5])

In [70]:
M.flatten()

array([4, 6, 7, 7, 8, 3, 0, 0, 2, 9, 3, 5])

In [71]:
M

array([[4, 6, 7],
       [7, 8, 3],
       [0, 0, 2],
       [9, 3, 5]])

In [72]:
M.T

array([[4, 7, 0, 9],
       [6, 8, 0, 3],
       [7, 3, 2, 5]])

In [73]:
M.min()

0

In [79]:
M.min(axis=1)   # min in all the column

array([4, 3, 0, 3])

In [80]:
M.min(axis=0)  # min in all the rows

array([0, 0, 2])

In [76]:
M.sum(axis=1)

array([17, 18,  2, 17])

In [77]:
M.min(axis=0)

array([0, 0, 2])

In [78]:
M.sum(axis=0)

array([20, 17, 17])

In [83]:
M.argmax()

9

In [84]:
M.argmin()

6

In [85]:
M = M.astype(np.int16)

In [86]:
M

array([[4, 6, 7],
       [7, 8, 3],
       [0, 0, 2],
       [9, 3, 5]], dtype=int16)

In [87]:
x

array([ 2,  4,  6,  8, 10], dtype=int8)

In [88]:
y

array([3. , 6. , 9.9, 5. , 4. ])

In [89]:
y=x

In [90]:
x

array([ 2,  4,  6,  8, 10], dtype=int8)

In [91]:
x

array([ 2,  4,  6,  8, 10], dtype=int8)

In [92]:
y[0]=20

In [93]:
y

array([20,  4,  6,  8, 10], dtype=int8)

In [94]:
x

array([20,  4,  6,  8, 10], dtype=int8)

In [95]:
id(x)

1991395517968

In [96]:
id(y)

1991395517968

In [97]:
y=x.copy()

In [98]:
id(x)

1991395517968

In [99]:
id(y)

1991413526384

In [100]:
y[0]=15

In [101]:
y

array([15,  4,  6,  8, 10], dtype=int8)

In [102]:
x

array([20,  4,  6,  8, 10], dtype=int8)