In [8]:
import tensorflow as tf
import numpy as np

In [2]:
tf

<module 'tensorflow' from 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\__init__.py'>

In [3]:
#Create Tensors
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
print('Tensor a=',a)
print('Tensor b=',b)

Tensor a= tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor b= tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [4]:
a[1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [9]:
#Create Tensors
x=tf.constant([[1,2,3], [7,8,9]], dtype=np.int8)
y=tf.constant([[4,5], [6,2]])
print('Tensor x=',x)
print('Tensor y=',y)

Tensor x= tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int8)
Tensor y= tf.Tensor(
[[4 5]
 [6 2]], shape=(2, 2), dtype=int32)


In [11]:
#Create Tensors
x1=tf.constant([[[1,2,3], [7,8,9]],[[2,2,3], [2,1,1]]], dtype=np.int8)
y1=tf.constant([[4,5], [6,2]])
print('Tensor x1=',x1)
print('Tensor y1=',y1)

Tensor x1= tf.Tensor(
[[[1 2 3]
  [7 8 9]]

 [[2 2 3]
  [2 1 1]]], shape=(2, 2, 3), dtype=int8)
Tensor y1= tf.Tensor(
[[4 5]
 [6 2]], shape=(2, 2), dtype=int32)


In [12]:
c=tf.add(a,b)
print('Addition c=', c)

Addition c= tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [13]:
a+b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [14]:
a-b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

In [15]:
c.numpy()

array([5, 7, 9])

In [16]:
a*b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

In [17]:
a/b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [19]:
a//b # only interger part after divide

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [20]:
b//a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 2])>

In [21]:
b/a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2.5, 2. ])>

In [25]:
# Matrix Multiplication
a_matrix = tf.constant([[1,2],[3,4]])
b_matrix = tf.constant([[5,6],[7,8]])
g=tf.matmul(a_matrix,b_matrix)
print('After Multiplication', g)

After Multiplication tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
